### ISSUE TITLE
Can I use your weights for my commercial app?

### ISSUE THREAD

**Issue by y-ich** [pangafu/LeelaMasterWeight#16]
Hi.

I am an author of iOS app "A Master of Go".
Is it possible to use your weights for my app?
Please tell me know conditions which you require.
(I am not quite sure what GPL means for trained weights...)

Thank you!

**Comment by pangafu** [comment]
Yes, welcome~

Please add link of leelamaster github url, and weight contributor is 章鱼围棋(Octopus Go) & 袁泉(pangafu@github)

**Comment by y-ich** [comment]
@pangafu san, thank you!
I will do it!

**Comment by y-ich** [comment]
The latest release has been public today and was too late to include your weights.
Since this release has the functionality to download extra weights, I prepared converted weight and make the link public on my repository.

https://github.com/new3Rs/a_master_of_go

I put the link of leelamaster github url, and weight contributor names here.

Thank you!

**Comment by pangafu** [comment]
Welcome~
