### ISSUE TITLE
I'm a big fan of your weights.

### ISSUE THREAD

**Issue by 22nsuk** [pangafu/LeelaMasterWeight#22]
I like the weights you have trained very much.
Recently no new weights have been uploaded, have you stopped training the weights?
If you are still training for new weights, I wonder if it is possible for you to release them.
I always thank you for your hard work.

**Comment by pangafu** [comment]
Please keep patient, the new weight not start until now.

**Comment by 22nsuk** [comment]
> Please keep patient, the new weight not start until now.

I see. Thank you for your reply.
